machine:
  node:
    version: 6.10.3
  environment:
    CONTINUOUS_INTEGRATION: true
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  override:
    - yarn
    - sudo pip install awscli
  cache_directories:
    - ~/.cache/yarn

test:
  override:
    - yarn run lint
    - yarn test
    - yarn build

deployment:
  master:
    branch: master
    commands:
      - yarn build
      - aws s3 sync build/ s3: //aws-website-personal-website-michael-sweetland-lzyc7
